<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>thetis-radiosim</AssemblyName>
    <Nullable>disable</Nullable>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>
</Project>
