// <auto-generated>
// Copied verbatim from Project Files/Source/Console/cmaster.cs by
// Linux/tools/sync_upstream.py -- do not edit; re-run the script instead.
// </auto-generated>
using System;
using System.Runtime.InteropServices;

namespace Thetis
{
    unsafe partial class cmaster
    {
        #region cmaster method definitions

        // cmaster

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRadioStructure", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRadioStructure(
            int cmSTREAM,			// total number of input streams to set up
            int cmRCVR,				// number of receivers to set up
            int cmXMTR,				// number of transmitters to set up
            int cmSubRCVR,			// number of sub-receivers per receiver to set up
            int cmNspc,				// number of TYPES of special units
            int* cmSPC,				// number of special units of each type
            int* cmMAXInbound,		// maximum number of samples in a call to Inbound()
            int cmMAXInRate,		// maximum sample rate of an input stream
            int cmMAXAudioRate,		// maximum channel audio output rate (incl. rcvr and tx monitor audio)
            int cmMAXTxOutRate		// maximum transmitter channel output sample rate
            );

        [DllImport("ChannelMaster.dll", EntryPoint = "CreateRadio", CallingConvention = CallingConvention.Cdecl)]
        public static extern void CreateRadio();

        [DllImport("ChannelMaster.dll", EntryPoint = "DestroyRadio", CallingConvention = CallingConvention.Cdecl)]
        public static extern void DestroyRadio();

        [DllImport("ChannelMaster.dll", EntryPoint = "set_cmdefault_rates", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetCMDefaultRates(int* xcm_inrates, int aud_outrate, int* rcvr_ch_outrates, int* xmtr_ch_outrates);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetXcmInrate", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetXcmInrate(int in_id, int rate);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetXmtrChannelOutrate", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetXmtrChannelOutrate(int xmtr_id, int rate, bool state);

        [DllImport("ChannelMaster.dll", EntryPoint = "getbuffsize", CallingConvention = CallingConvention.Cdecl)]
        public static extern int GetBuffSize (int rate);

        [DllImport("ChannelMaster.dll", EntryPoint = "inid", CallingConvention = CallingConvention.Cdecl)]
        public static extern int inid(int stype, int id);

        [DllImport("ChannelMaster.dll", EntryPoint = "Inbound", CallingConvention = CallingConvention.Cdecl)]
        public static extern void Inbound(int id, int nsamples, double* data);

        [DllImport("ChannelMaster.dll", EntryPoint = "chid", CallingConvention = CallingConvention.Cdecl)]
        public static extern int chid (int stream, int subrx);

        [DllImport("ChannelMaster.dll", EntryPoint = "getInputRate", CallingConvention = CallingConvention.Cdecl)]
        public static extern int GetInputRate (int stype, int id);

        [DllImport("ChannelMaster.dll", EntryPoint = "getChannelOutputRate", CallingConvention = CallingConvention.Cdecl)]
        public static extern int GetChannelOutputRate(int stype, int id);

        [DllImport("ChannelMaster.dll", EntryPoint = "getCMAstate", CallingConvention = CallingConvention.Cdecl)]
        public static extern int GetCMAstate();

        // tci
        [DllImport("ChannelMaster.dll", EntryPoint = "SendpOutboundTCIRxIQ", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SendpOutboundTCIRxIQ(TCIStreamSamples del);

        [DllImport("ChannelMaster.dll", EntryPoint = "SendpOutboundTCIRxAudio", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SendpOutboundTCIRxAudio(TCIStreamSamples del);

        [DllImport("ChannelMaster.dll", EntryPoint = "SendpInboundTCITxAudio", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SendpInboundTCITxAudio(TCITxInput del);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRXTCIRun", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRXTCIRun(int active);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetTXTCIAudioRun", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetTXTCIAudioRun(int txid, int active);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetTCIRxAudioMox", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetTCIRxAudioMox(int id, int mox);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetTCIRxAudioMon", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetTCIRxAudioMon(int id, int mon);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetTCIRxAudioMonVol", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetTCIRxAudioMonVol(int id, double vol);
        // end tci

        // router
        [DllImport("ChannelMaster.dll", EntryPoint = "LoadRouterAll", CallingConvention = CallingConvention.Cdecl)]
        public static extern void LoadRouterAll(void* ptr, int id, int sources, int calls, int varvals, 
            int* nstreams, int* function, int* callid);

        [DllImport("ChannelMaster.dll", EntryPoint = "LoadRouterControlBit", CallingConvention = CallingConvention.Cdecl)]
        public static extern void LoadRouterControlBit(void* ptr, int id, int var_number, int bit);

        // display setup

        [DllImport("ChannelMaster.dll", EntryPoint = "SetTopPan3Run", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetTopPan3Run(bool run);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRunPanadapter", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRunPanadapter(int id, bool run);

        // puresignal setup

        [DllImport("ChannelMaster.dll", EntryPoint = "SetPSTxIdx", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSTxIdx(int id, int idx);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetPSRxIdx", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSRxIdx(int id, int idx);

        // cmaster multiple analyzers
        [DllImport("ChannelMaster.dll", EntryPoint = "alloc_analyzer", CallingConvention = CallingConvention.Cdecl)]
        public static extern int AllocAnalyzer(int stype, int id, int max_fft_size);
        [DllImport("ChannelMaster.dll", EntryPoint = "free_analyzer", CallingConvention = CallingConvention.Cdecl)]
        public static extern int FreeAnalyzer(int disp);

        [DllImport("ChannelMaster.dll", EntryPoint = "run_analyzer", CallingConvention = CallingConvention.Cdecl)]
        public static extern int RunAnalyzer(int disp, int run);

        // vox-dexp

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPAttackThreshold", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetTXAVoxThresh(int id, double thresh);

        [DllImport("wdsp.dll", EntryPoint = "GetDEXPPeakSignal", CallingConvention = CallingConvention.Cdecl)]
        public static extern void GetDEXPPeakSignal(int id, double* peak);         // called by console.cs

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPRun", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPRun (int id, bool run);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPDetectorTau", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPDetectorTau(int id, double tau);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPAttackTime", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPAttackTime(int id, double time);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPReleaseTime", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPReleaseTime(int id, double time);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPHoldTime", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPHoldTime(int id, double time);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPExpansionRatio", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPExpansionRatio(int id, double ratio);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPHysteresisRatio", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPHysteresisRatio(int id, double ratio);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPAttackThreshold", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPAttackThreshold(int id, double thresh);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPLowCut", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPLowCut(int id, double lowcut);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPHighCut", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPHighCut(int id, double highcut);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPRunSideChannelFilter", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPRunSideChannelFilter(int id, bool run);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPRunVox", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPRunVox(int id, bool run);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPRunAudioDelay", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPRunAudioDelay(int id, bool run);

        [DllImport("wdsp.dll", EntryPoint = "SetDEXPAudioDelay", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetDEXPAudioDelay(int id, double delay);

        [DllImport("wdsp.dll", EntryPoint = "SetAntiVOXRun", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetAntiVOXRun(int id, bool run);

        [DllImport("wdsp.dll", EntryPoint = "SetAntiVOXGain", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetAntiVOXGain(int id, double gain);

        [DllImport("wdsp.dll", EntryPoint = "SetAntiVOXDetectorTau", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetAntiVOXDetectorTau(int id, double tau);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetAntiVOXSourceStates", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetAntiVOXSourceStates(int txid, int streams, int states);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetAntiVOXSourceWhat", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetAntiVOXSourceWhat(int txid, int stream, int state);

        // siphon

        [DllImport("wdsp.dll", EntryPoint = "SetSiphonInsize", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetSiphonInsize (int id, int size);

        [DllImport("wdsp.dll", EntryPoint = "GetaSipF1EXT", CallingConvention = CallingConvention.Cdecl)]
        public static extern void GetaSipF1EXT (int id, float* buff, int size);     // called by console.cs

        // audio mixer

        [DllImport("ChannelMaster.dll", EntryPoint = "SetAAudioMixWhat", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetAAudioMixWhat(void* ptr, int id, int stream, bool state);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetAAudioMixState", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetAAudioMixState(void* ptr, int id, int stream, bool state);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetAAudioMixStates", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetAAudioMixStates(void* ptr, int id, int streams, int states);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetAAudioMixVolume", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetAAudioMixVolume(void* ptr, int id, double volume);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetAAudioMixVol", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetAAudioMixVol(void* ptr, int id, int stream, double vol);

        // VAC transmit audio selection

        [DllImport("ChannelMaster.dll", EntryPoint = "SetTXVAC", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetTXVAC(int txid, int txvac);

        // Penelope output level

        [DllImport("ChannelMaster.dll", EntryPoint = "SetTXFixedGainRun", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetTXFixedGainRun(int id, bool run);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetTXFixedGain", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetTXFixedGain(int id, double Igain, double Qgain);

        // eer/etr

        [DllImport("ChannelMaster.dll", EntryPoint = "SetEERRun", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetEERRun(int id, bool run);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetEERAMIQ", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetEERAMIQ(int id, bool amiq);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetEERMgain", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetEERMgain(int id, double gain);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetEERPgain", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetEERPgain(int id, double gain);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetEERRunDelays", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetEERRunDelays(int id, bool run);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetEERMdelay", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetEERMdelay(int id, double delay);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetEERPdelay", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetEERPdelay(int id, double delay);

        // noise blanker - call directly from various places

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRANBRun", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRANBRun(int stype, int id, bool run);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRANBTau", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRANBTau(int stype, int id, double tau);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRANBHangtime", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRANBHangtime(int stype, int id, double time);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRANBAdvtime", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRANBAdvtime(int stype, int id, double time);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRANBBacktau", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRANBBacktau(int stype, int id, double tau);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRANBThreshold", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRANBThreshold(int stype, int id, double thresh);

        // noise blanker II - call directly from various places

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRNOBRun", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRNOBRun(int stype, int id, bool run);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRNOBMode", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRNOBMode(int stype, int id, int mode);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRNOBTau", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRNOBTau(int stype, int id, double tau);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRNOBHangtime", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRNOBHangtime(int stype, int id, double time);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRNOBAdvtime", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRNOBAdvtime(int stype, int id, double time);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRNOBBacktau", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRNOBBacktau(int stype, int id, double tau);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetRCVRNOBThreshold", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetRCVRNOBThreshold(int stype, int id, double thresh);

        // external amplifier protection

        [DllImport("ChannelMaster.dll", EntryPoint = "GetAndResetAmpProtect", CallingConvention = CallingConvention.Cdecl)]
        extern public static int GetAndResetAmpProtect(int txid);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetAmpProtectRun", CallingConvention = CallingConvention.Cdecl)]
        extern public static void SetAmpProtectRun(int txid, int run);

        [DllImport("ChannelMaster.dll", EntryPoint = "SetADCSupply", CallingConvention = CallingConvention.Cdecl)]
        extern public static void SetADCSupply(int txid, int v);

        // monitoring & debugging

        [DllImport("ChannelMaster.dll", EntryPoint = "getLEDs", CallingConvention = CallingConvention.Cdecl)]
        extern public static int getLEDs();

        // version
        [DllImport("ChannelMaster.dll", EntryPoint = "GetCMVersion", CallingConvention = CallingConvention.Cdecl)]
        extern public static int GetCMVersion();

        [DllImport("cmASIO.dll", EntryPoint = "GetCMasioVersion", CallingConvention = CallingConvention.Cdecl)]
        extern public static int GetCMasioVersion();
        #endregion

        unsafe public delegate void TCIStreamSamples(int id, int nsamples, double* data);
        unsafe public delegate void TCITxInput(int nsamples, double* data);

        public static void CMLoadRouterAll(HPSDRModel model)
        {
            int txinid = cmaster.inid(1, 0);        // stream id
            int txch = cmaster.chid(txinid, 0);     // wdsp channel

            puresignal.SetPSHWPeak(txch, HardwareSpecific.PSDefaultPeak);   // MI0BOT: Correct for correct PS value

            switch (NetworkIO.CurrentRadioProtocol)
            {
                case RadioProtocol.USB: //Protocol 1
                    if (ps_loopback)
                    {
                        switch (model)
                        {
                            case HPSDRModel.ANAN10E:
                            case HPSDRModel.ANAN100B:
                                int[] TWO_DDC_Function = new int[16]
                                    {
                                    2, 2, 2, 2, 2, 2, 2, 2,     // DDC0+DDC1, port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2      // DDC0+DDC1, port 1035, Call 1
                                    };
                                int[] TWO_DDC_Callid = new int[16]
                                    {
                                    2, 2, 2, 2, 2, 1, 2, 1,      // DDC0+DDC1, port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2       // DDC0+DDC1, port 1035, Call 1
                                    };
                                int[] TWO_DDC_nstreams = new int[1]
                                    {
                                    2                           // DDC0+DDC1, port 1035
                                    };
                                fixed (int* pstreams = &TWO_DDC_nstreams[0], pfunction = &TWO_DDC_Function[0], pcallid = &TWO_DDC_Callid[0])
                                    LoadRouterAll((void*)0, 0, 1, 2, 8, pstreams, pfunction, pcallid);
                                break;
                            case HPSDRModel.HERMES:
                            case HPSDRModel.ANAN_G2E: //N1GP G2E added
                            case HPSDRModel.HERMESLITE: // MI0BOT: HL2
                            case HPSDRModel.ANAN10:
                            case HPSDRModel.ANAN100:
                                int[] FOUR_DDC_Function = new int[48]
                                    {
                                    1, 1, 1, 1, 1, 0, 1, 0,     // DDC0,      port 1035, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // DDC0,      port 1035, Call 1
                                    0, 0, 0, 0, 0, 2, 0, 2,     // DDC2+DDC3, port 1036, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // DDC2+DDC3, port 1036, Call 1
                                    1, 1, 1, 1, 1, 0, 1, 0,     // DDC1,      port 1037, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0      // DDC1,      port 1037, Call 1
                                    };
                                int[] FOUR_DDC_Callid = new int[48]
                                    {
                                    0, 0, 0, 0, 0, 0, 0, 0,     // DDC0,      port 1035, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // DDC0,      port 1035, Call 1
                                    0, 0, 0, 0, 0, 1, 0, 1,     // DDC2+DDC3, port 1036, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // DDC2+DDC3, port 1036, Call 1
                                    1, 1, 1, 1, 1, 0, 1, 0,     // DDC1,      port 1037, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0      // DDC1,      port 1037, Call 1
                                    };
                                int[] FOUR_DDC_nstreams = new int[3]
                                    {
                                    1,                          // DDC0,      port 1035
                                    2,                          // DDC2+DDC3, port 1036
                                    1                           // DDC1,      port 1037
                                    };
                                fixed (int* pstreams = &FOUR_DDC_nstreams[0], pfunction = &FOUR_DDC_Function[0], pcallid = &FOUR_DDC_Callid[0])
                                    LoadRouterAll((void*)0, 0, 3, 2, 8, pstreams, pfunction, pcallid);
                                break;
                            case HPSDRModel.ANAN100D:
                            case HPSDRModel.ANAN200D:
                            case HPSDRModel.ORIONMKII:
                            case HPSDRModel.ANAN7000D:
                            case HPSDRModel.ANAN8000D:
                            case HPSDRModel.ANVELINAPRO3:
                            case HPSDRModel.REDPITAYA: //DH1KLM
                                int[] FIVE_DDC_Function = new int[48]
                                    {
                                    2, 2, 2, 2, 2, 0, 2, 0,     // DDC0+DDC1, port 1035, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // DDC0+DDC1, port 1035, Call 1
                                    0, 0, 0, 0, 0, 2, 0, 2,     // DDC3+DDC4, port 1036, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // DDC3+DDC4, port 1036, Call 1
                                    1, 1, 1, 1, 1, 0, 1, 0,     // DDC2,      port 1037, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0      // DDC2,      port 1037, Call 1
                                    };
                                int[] FIVE_DDC_Callid = new int[48]
                                    {
                                    3, 3, 0, 0, 3, 0, 0, 0,     // DDC0+DDC1, port 1035, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // DDC0+DDC1, port 1035, Call 1
                                    0, 0, 0, 0, 0, 1, 0, 1,     // DDC3+DDC4, port 1036, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // DDC3+DDC4, port 1036, Call 1
                                    1, 1, 1, 1, 1, 0, 1, 0,     // DDC2,      port 1037, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0      // DDC2,      port 1037, Call 1
                                    };
                                int[] FIVE_DDC_nstreams = new int[3]
                                    {
                                    2,                          // DDC0+DDC1, port 1035
                                    2,                          // DDC1+DDC4, port 1036
                                    1                           // DDC2,      port 1037
                                    };
                                fixed (int* pstreams = &FIVE_DDC_nstreams[0], pfunction = &FIVE_DDC_Function[0], pcallid = &FIVE_DDC_Callid[0])
                                    LoadRouterAll((void*)0, 0, 3, 2, 8, pstreams, pfunction, pcallid);
                                break;
                        }
                    }
                    else
                    {
                        switch (model)
                        {
                            case HPSDRModel.ANAN10E:
                            case HPSDRModel.ANAN100B:
                                int[] TWO_DDC_Function = new int[16]
                                    {
                                    2, 2, 2, 2, 2, 2, 2, 2,     // DDC0+DDC1, port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2      // DDC0+DDC1, port 1035, Call 1 Sends TX_freq data to both RX //MW0LGE_21d DUP on top panadaptor (Warren provided info)
                                    };
                                int[] TWO_DDC_Callid = new int[16]
                                    {
                                    2, 2, 2, 2, 2, 1, 2, 1,      // DDC0+DDC1, port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2      // DDC0+DDC1, port 1035, Call 1 Sends TX_freq data to both RX //MW0LGE_21d DUP on top panadaptor (Warren provided info), // MW0LGE [2.9.0.8] from Warren, change 3's to 2's
                                    };
                                int[] TWO_DDC_nstreams = new int[1]
                                    {
                                    2                           // DDC0+DDC1, port 1035
                                    };
                                fixed (int* pstreams = &TWO_DDC_nstreams[0], pfunction = &TWO_DDC_Function[0], pcallid = &TWO_DDC_Callid[0])
                                    LoadRouterAll((void*)0, 0, 1, /*1*/2, 8, pstreams, pfunction, pcallid); //MW0LGE_21d DUP on top panadaptor (Warren provided info)
                                break;
                            case HPSDRModel.HERMES:
                            case HPSDRModel.ANAN_G2E: //N1GP G2E added
                            case HPSDRModel.HERMESLITE: // MI0BOT: HL2
                            case HPSDRModel.ANAN10:
                            case HPSDRModel.ANAN100:
                                int[] FOUR_DDC_Function = new int[24]
                                    {
                                    1, 1, 1, 1, 1, 1, 1, 1,     // DDC0,      port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // DDC2+DDC3, port 1036, Call 0
                                    1, 1, 1, 1, 1, 1, 1, 1      // DDC1,      port 1037, Call 0
                                    };
                                int[] FOUR_DDC_Callid = new int[24]
                                    {
                                    0, 0, 0, 0, 0, 0, 0, 0,     // DDC0,      port 1035, Call 0
                                    0, 0, 0, 0, 0, 1, 0, 1,     // DDC2+DDC3, port 1036, Call 0
                                    1, 1, 1, 1, 1, 1, 1, 1      // DDC1,      port 1037, Call 0
                                    };
                                int[] FOUR_DDC_nstreams = new int[3]
                                    {
                                    1,                          // DDC0,      port 1035
                                    2,                          // DDC2+DDC3, port 1036
                                    1                           // DDC1,      port 1037
                                    };
                                fixed (int* pstreams = &FOUR_DDC_nstreams[0], pfunction = &FOUR_DDC_Function[0], pcallid = &FOUR_DDC_Callid[0])
                                    LoadRouterAll((void*)0, 0, 3, 1, 8, pstreams, pfunction, pcallid);
                                break;
                            case HPSDRModel.ANAN100D:
                            case HPSDRModel.ANAN200D:
                            case HPSDRModel.ORIONMKII:
                            case HPSDRModel.ANAN7000D:
                            case HPSDRModel.ANAN8000D:
                            case HPSDRModel.ANVELINAPRO3:
                            case HPSDRModel.REDPITAYA: //DH1KLM
                                int[] FIVE_DDC_Function = new int[24]
                                    {
                                    2, 2, 2, 2, 2, 2, 2, 2,     // DDC0+DDC1, port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // DDC3+DDC4, port 1036, Call 0
                                    1, 1, 1, 1, 1, 1, 1, 1      // DDC2,      port 1037, Call 0
                                    };
                                int[] FIVE_DDC_Callid = new int[24]
                                    {
                                    3, 3, 0, 0, 3, 3, 0, 0,     // DDC0+DDC1, port 1035, Call 0
                                    0, 0, 0, 0, 0, 1, 0, 1,     // DDC3+DDC4, port 1036, Call 0
                                    1, 1, 1, 1, 1, 1, 1, 1      // DDC2,      port 1037, Call 0
                                    };
                                int[] FIVE_DDC_nstreams = new int[3]
                                    {
                                    2,                          // DDC0+DDC1, port 1035
                                    2,                          // DDC3+DDC4, port 1036
                                    1                           // DDC2,      port 1037
                                    };
                                fixed (int* pstreams = &FIVE_DDC_nstreams[0], pfunction = &FIVE_DDC_Function[0], pcallid = &FIVE_DDC_Callid[0])
                                    LoadRouterAll((void*)0, 0, 3, 1, 8, pstreams, pfunction, pcallid);
                                break;
                        }
                    }
                    break;
                case RadioProtocol.ETH: //Protocol 2
                    if (ps_loopback)    // for test purposes
                    {
                        switch (model)
                        {
                            case HPSDRModel.ANAN100D:
                            case HPSDRModel.ANAN200D:
                            case HPSDRModel.ORIONMKII:
                            case HPSDRModel.ANAN7000D:
                            case HPSDRModel.ANAN8000D:
                            case HPSDRModel.ANVELINAPRO3:
                            case HPSDRModel.REDPITAYA: //DH1KLM
                            case HPSDRModel.ANAN_G2:
                            case HPSDRModel.ANAN_G2_1K:
                                // This ANGELIA table is for test purposes and it routes DDC0 and DDC1 to RX1 and RX2, 
                                //      respectively, (as well as to PureSignal) when transmitting with PureSignal 
                                //      Enabled in Setup.
                                // control bits are { MOX, Diversity_Enabled, PureSignal_Enabled }
                                int[] Angelia_Function_PSTest = new int[112] 
                                { 
                                    0, 0, 2, 2, 0, 2, 2, 2,     // Rx0, port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // Rx0, port 1035, Call 1
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx1, port 1036, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx1, port 1036, Call 1
                                    1, 1, 0, 0, 1, 0, 0, 0,     // Rx2, port 1037, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx2, port 1037, Call 1
                                    1, 1, 1, 1, 1, 0, 1, 0,     // Rx3, port 1038, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx3, port 1038, Call 1
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx4, port 1039, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx4, port 1039, Call 1
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx5, port 1040, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx5, port 1040, Call 1
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx6, port 1041, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0      // Rx6, port 1041, Call 1
                                };
                                int[] Angelia_Callid_PSTest = new int[112]
                                {
                                    0, 0, 0, 0, 0, 1, 0, 1,     // Rx0, port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // Rx0, port 1035, Call 1
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx1, port 1036, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx1, port 1036, Call 1
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx2, port 1037, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx2, port 1037, Call 1
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx3, port 1038, Call 0
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx3, port 1038, Call 1
                                    2, 2, 2, 2, 2, 2, 2, 2,     // Rx4, port 1039, Call 0
                                    2, 2, 2, 2, 2, 2, 2, 2,     // Rx4, port 1039, Call 1
                                    3, 3, 3, 3, 3, 3, 3, 3,     // Rx5, port 1040, Call 0
                                    3, 3, 3, 3, 3, 3, 3, 3,     // Rx5, port 1040, Call 1
                                    4, 4, 4, 4, 4, 4, 4, 4,     // Rx6, port 1041, Call 0
                                    4, 4, 4, 4, 4, 4, 4, 4      // Rx6, port 1041, Call 1
                                };
                                int[] Angelia_nstreams_PSTest = new int[7]
                                {
                                    2,                          // Rx0, port 1035
                                    1,                          // Rx1, port 1036
                                    1,                          // Rx2, port 1037
                                    1,                          // Rx3, port 1038
                                    1,                          // Rx4, port 1039
                                    1,                          // Rx5, port 1040
                                    1                           // Rx6, port 1041
                                };
                                fixed (int* pstreams = &Angelia_nstreams_PSTest[0], pfunction = &Angelia_Function_PSTest[0], pcallid = &Angelia_Callid_PSTest[0])
                                    LoadRouterAll((void*)0, 0, 7, 2, 8, pstreams, pfunction, pcallid);
                                break;

                            case HPSDRModel.HERMES:
                            case HPSDRModel.ANAN_G2E: //N1GP G2E added
                            case HPSDRModel.HERMESLITE: // MI0BOT: HL2
                            case HPSDRModel.ANAN10:
                            case HPSDRModel.ANAN100:
                            case HPSDRModel.ANAN10E:
                            case HPSDRModel.ANAN100B:
                                int[] HermesE_Function = new int[32]
                                {
                                    1, 1, 2, 2, 1, 2, 2, 2,     // Rx0, port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // Rx0, port 1035, Call 1
                                    1, 1, 0, 0, 1, 0, 0, 0,     // Rx1, port 1036, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0      // Rx1, port 1036, Call 1
                                };
                                int[] HermesE_Callid = new int[32]
                                {
                                    0, 0, 0, 0, 0, 1, 0, 1,     // Rx0, port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // Rx0, port 1035, Call 1
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx1, port 1036, Call 0
                                    1, 1, 1, 1, 1, 1, 1, 1      // Rx1, port 1036, Call 1
                                };
                                int[] HermesE_nstreams = new int[2]
                                {
                                    2,                          // Rx0, port 1035
                                    1                           // Rx1, port 1036
                                };
                                fixed (int* pstreams = &HermesE_nstreams[0], pfunction = &HermesE_Function[0], pcallid = &HermesE_Callid[0])
                                    LoadRouterAll((void*)0, 0, 2, 2, 8, pstreams, pfunction, pcallid);
                                break;
                        }
                    }
                    else
                    {
                        switch (model)
                        {
                            case HPSDRModel.ANAN100D:
                            case HPSDRModel.ANAN200D:
                            case HPSDRModel.ORIONMKII:
                            case HPSDRModel.ANAN7000D:
                            case HPSDRModel.ANAN8000D:
                            case HPSDRModel.ANVELINAPRO3:
                            case HPSDRModel.REDPITAYA: //DH1KLM
                            case HPSDRModel.ANAN_G2:
                            case HPSDRModel.ANAN_G2_1K:
                                // control bits are { MOX, Diversity_Enabled, PureSignal_Enabled }
                                int[] Angelia_Function = new int[56] 
                                { 
                                    0, 0, 2, 2, 0, 2, 2, 2,     // Rx0, port 1035
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx1, port 1036
                                    1, 1, 0, 0, 1, 1, 0, 1,     // Rx2, port 1037
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx3, port 1038
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx4, port 1039
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx5, port 1040
                                    1, 1, 1, 1, 1, 1, 1, 1      // Rx6, port 1041
                                };
                                int[] Angelia_Callid = new int[56]
                                {
                                    0, 0, 0, 0, 0, 1, 0, 1,     // Rx0, port 1035
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx1, port 1036
                                    0, 0, 0, 0, 0, 0, 0, 0,     // Rx2, port 1037
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx3, port 1038
                                    2, 2, 2, 2, 2, 2, 2, 2,     // Rx4, port 1039
                                    3, 3, 3, 3, 3, 3, 3, 3,     // Rx5, port 1040
                                    4, 4, 4, 4, 4, 4, 4, 4      // Rx6, port 1041
                                };
                                int[] Angelia_nstreams = new int[7]
                                {
                                    2,                          // Rx0, port 1035
                                    1,                          // Rx1, port 1036
                                    1,                          // Rx2, port 1037
                                    1,                          // Rx3, port 1038
                                    1,                          // Rx4, port 1039
                                    1,                          // Rx5, port 1040
                                    1                           // Rx6, port 1041
                                };
                                fixed (int* pstreams = &Angelia_nstreams[0], pfunction = &Angelia_Function[0], pcallid = &Angelia_Callid[0])
                                    LoadRouterAll((void*)0, 0, 7, 1, 8, pstreams, pfunction, pcallid);
                                break;

                            case HPSDRModel.HERMES:
                            case HPSDRModel.ANAN_G2E: //N1GP G2E added
                            case HPSDRModel.HERMESLITE: // MI0BOT: HL2
                            case HPSDRModel.ANAN10:
                            case HPSDRModel.ANAN100:
                            case HPSDRModel.ANAN10E:
                            case HPSDRModel.ANAN100B:
                                int[] HermesE_Function = new int[32]
                                {
                                    1, 1, 2, 2, 1, 2, 2, 2,     // Rx0, port 1035, Call 0
                                    0, 0, 0, 0, 0, 2, 0, 2,     // Rx0, port 1035, Call 1
                                    1, 1, 0, 0, 1, 0, 0, 0,     // Rx1, port 1036, Call 0
                                    0, 0, 0, 0, 0, 0, 0, 0      // Rx1, port 1036, Call 1
                                };
                                int[] HermesE_Callid = new int[32]
                                {
                                    0, 0, 0, 0, 0, 1, 0, 1,     // Rx0, port 1035, Call 0
                                    0, 0, 0, 0, 0, 3, 0, 3,     // Rx0, port 1035, Call 1
                                    1, 1, 1, 1, 1, 1, 1, 1,     // Rx1, port 1036, Call 0
                                    1, 1, 1, 1, 1, 1, 1, 1      // Rx1, port 1036, Call 1
                                };
                                int[] HermesE_nstreams = new int[2]
                                {
                                    2,                          // Rx0, port 1035
                                    1                           // Rx1, port 1036
                                };
                                fixed (int* pstreams = &HermesE_nstreams[0], pfunction = &HermesE_Function[0], pcallid = &HermesE_Callid[0])
                                    LoadRouterAll((void*)0, 0, 2, 2, 8, pstreams, pfunction, pcallid);
                                break;
                            case HPSDRModel.HPSDR:

                                break;
                        }
                    }
                    break;
            }
        }
    }
}
