// <auto-generated>
// Copied verbatim from Project Files/Source/Console/PSForm.cs by
// Linux/tools/sync_upstream.py -- do not edit; re-run the script instead.
// </auto-generated>
using System;
using System.Drawing;
using System.Runtime.InteropServices;

namespace Thetis
{
    unsafe static class puresignal
    {
        #region DllImport - Main

        [DllImport("wdsp.dll", EntryPoint = "SetPSRunCal", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSRunCal(int channel, bool run);

        [DllImport("wdsp.dll", EntryPoint = "SetPSMox", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSMox(int channel, bool mox);

        [DllImport("wdsp.dll", EntryPoint = "GetPSInfo", CallingConvention = CallingConvention.Cdecl)]
        public static extern void GetPSInfo(int channel, int* info);

        [DllImport("wdsp.dll", EntryPoint = "SetPSReset", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSReset(int channel, int reset);

        [DllImport("wdsp.dll", EntryPoint = "SetPSMancal", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSMancal(int channel, int mancal);

        [DllImport("wdsp.dll", EntryPoint = "SetPSAutomode", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSAutomode(int channel, int automode);

        [DllImport("wdsp.dll", EntryPoint = "SetPSTurnon", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSTurnon(int channel, int turnon);

        [DllImport("wdsp.dll", EntryPoint = "SetPSControl", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSControl(int channel, int reset, int mancal, int automode, int turnon);

        [DllImport("wdsp.dll", EntryPoint = "SetPSLoopDelay", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSLoopDelay(int channel, double delay);

        [DllImport("wdsp.dll", EntryPoint = "SetPSMoxDelay", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSMoxDelay(int channel, double delay);

        [DllImport("wdsp.dll", EntryPoint = "SetPSTXDelay", CallingConvention = CallingConvention.Cdecl)]
        public static extern double SetPSTXDelay(int channel, double delay);

        [DllImport("wdsp.dll", EntryPoint = "psccF", CallingConvention = CallingConvention.Cdecl)]
        public static extern void psccF(int channel, int size, float* Itxbuff, float* Qtxbuff, float* Irxbuff, float* Qrxbuff, bool mox, bool solidmox);

        [DllImport("wdsp.dll", EntryPoint = "PSSaveCorr", CallingConvention = CallingConvention.Cdecl)]
        public static extern void PSSaveCorr(int channel, string filename);

        [DllImport("wdsp.dll", EntryPoint = "PSRestoreCorr", CallingConvention = CallingConvention.Cdecl)]
        public static extern void PSRestoreCorr(int channel, string filename);

        [DllImport("wdsp.dll", EntryPoint = "SetPSHWPeak", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSHWPeak(int channel, double peak);

        [DllImport("wdsp.dll", EntryPoint = "GetPSHWPeak", CallingConvention = CallingConvention.Cdecl)]
        public static extern void GetPSHWPeak(int channel, double* peak);

        [DllImport("wdsp.dll", EntryPoint = "GetPSMaxTX", CallingConvention = CallingConvention.Cdecl)]
        public static extern void GetPSMaxTX(int channel, double* maxtx);

        [DllImport("wdsp.dll", EntryPoint = "SetPSPtol", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSPtol(int channel, double ptol);

        [DllImport("wdsp.dll", EntryPoint = "GetPSDisp", CallingConvention = CallingConvention.Cdecl)]
        public static extern void GetPSDisp(int channel, IntPtr x, IntPtr ym, IntPtr yc, IntPtr ys, IntPtr cm, IntPtr cc, IntPtr cs);

        [DllImport("wdsp.dll", EntryPoint = "SetPSFeedbackRate", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSFeedbackRate(int channel, int rate);

        [DllImport("wdsp.dll", EntryPoint = "SetPSPinMode", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSPinMode(int channel, int pin);

        [DllImport("wdsp.dll", EntryPoint = "SetPSMapMode", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSMapMode(int channel, int map);

        [DllImport("wdsp.dll", EntryPoint = "SetPSStabilize", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSStabilize(int channel, int stbl);

        [DllImport("wdsp.dll", EntryPoint = "SetPSIntsAndSpi", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPSIntsAndSpi(int channel, int ints, int spi);

        #endregion

        #region public methods
        private static int[] _info = new int[16];
        private static int[] _oldInfo = new int[16];
        private static bool _bInvertRedBlue = false;
        static puresignal()
        {
            for(int i = 0; i < 16; i++)
            {
                _info[i] = 0;
                _oldInfo[i] = _info[i];
            }
        }
        public static int[] Info
        {
            get { return _info; }
        }
        public static void GetInfo(int txachannel)
        {
            //make copy of old, used in HasInfoChanged & CalibrationAttemptsChanged MW0LGE
            fixed (void* dest = &_oldInfo[0])
            fixed (void* src = &_info[0])
                Win32.memcpy(dest, src, 16 * sizeof(int));

            fixed (int* ptr = &(_info[0]))
                GetPSInfo(txachannel, ptr);
        }       
        public static bool HasInfoChanged 
        {
            get {
                for (int n = 0; n < 16; n++)
                {
                    if (_info[n] != _oldInfo[n])
                        return true;
                }
                return false;
            }
        }
        public static bool CalibrationAttemptsChanged {
            get { return _info[5] != _oldInfo[5]; }
        }
        public static bool CorrectionsBeingApplied {
            get { return _info[14] == 1; }
        }
        public static int CalibrationCount {
            get { return _info[5]; }
        }
        public static bool Correcting {
            get { return FeedbackLevel > 90; }
        }
        public static bool NeedToRecalibrate(int nCurrentATTonTX) {
            //note: for reference (puresignal.Info[4] > 181 || (puresignal.Info[4] <= 128 && console.SetupForm.ATTOnTX > 0))
            return (FeedbackLevel > 181 || (FeedbackLevel <= 128 && nCurrentATTonTX > 0));            
        }
        
        public static bool NeedToRecalibrate_HL2(int nCurrentATTonTX) {
            //note: for reference (puresignal.Info[4] > 181 || (puresignal.Info[4] <= 128 && console.SetupForm.ATTOnTX > 0))
            return (FeedbackLevel > 181 || (FeedbackLevel <= 128 && nCurrentATTonTX > -28));    // MI0BOT: Needed seperate function for HL2 as           
        }                                                                                       //         great range in attenuation           
        public static bool IsFeedbackLevelOK {
            get { return FeedbackLevel <= 256; }
        }
        public static bool IsFeedbackLevelOKRange
        {
            get { return FeedbackLevel > 128 && FeedbackLevel <= 181; }
        }
        public static int FeedbackLevel {
            get { return _info[4]; }
        }
        public static Color FeedbackColourLevel {
            get {
                if (FeedbackLevel > 181)
                {
                    if (_bInvertRedBlue) return Color.Red;
                    return Color.DodgerBlue;
                }
                else if (FeedbackLevel > 128) return Color.Lime;
                else if (FeedbackLevel > 90) return Color.Yellow;
                else
                {
                    if (_bInvertRedBlue) return Color.DodgerBlue;
                    return Color.Red;
                }
            }
        }
        // info[15] is engine state (from calcc.c)
        public enum EngineState
        {
            LRESET = 0,
            LWAIT,
            LMOXDELAY,
            LSETUP,
            LCOLLECT,
            MOXCHECK,
            LCALC,
            LDELAY,
            LSTAYON,
            LTURNON
        };
        public static EngineState State {
            get { return (EngineState)_info[15]; }
        }

        public static bool InvertRedBlue
        {
            get { return _bInvertRedBlue; }
            set { _bInvertRedBlue = value; }
        }
        #endregion
    }
}
