#!/usr/bin/env python3
"""Regenerate Thetis.Core/Upstream/*.g.cs from the upstream Console sources.

Some upstream files cannot be compiled as-is on .NET 8 / Linux because they
are entangled with WinForms or the Console form, but contain large blocks
(P/Invoke tables, radio router tables) that must stay identical to upstream.
This script copies those blocks verbatim so they can be refreshed after an
upstream merge:  python3 tools/sync_upstream.py
"""
import pathlib, re

here = pathlib.Path(__file__).resolve().parent.parent
console = here.parent / "Console"
out_dir = here / "Thetis.Core" / "Upstream"
out_dir.mkdir(parents=True, exist_ok=True)


def block(text, start_pat, end_pat="\n        #endregion"):
    i = text.index(start_pat)
    j = text.index(end_pat, i)
    return text[i:j]


def method(text, signature):
    """Return a method from its signature line to its closing brace (8-space indent)."""
    i = text.index(signature)
    i = text.rindex("\n", 0, i) + 1
    j = text.index("\n        }\n", i) + len("\n        }\n")
    return text[i:j]


header = """// <auto-generated>
// Copied verbatim from Project Files/Source/Console/{src} by
// Linux/tools/sync_upstream.py -- do not edit; re-run the script instead.
// </auto-generated>
"""

cm = (console / "cmaster.cs").read_text(encoding="utf-8-sig")
imports = block(cm, "#region cmaster method definitions")
router = method(cm, "public static void CMLoadRouterAll(HPSDRModel model)")
delegates = "\n".join(l for l in cm.splitlines()
                      if re.match(r"\s*unsafe public delegate void TCI(StreamSamples|TxInput)\(", l))
(out_dir / "cmaster.g.cs").write_text(
    header.format(src="cmaster.cs")
    + "using System;\nusing System.Runtime.InteropServices;\n\nnamespace Thetis\n{\n"
    + "    unsafe partial class cmaster\n    {\n        "
    + imports.rstrip() + "\n        #endregion\n\n"
    + delegates + "\n\n"
    + router
    + "    }\n}\n", encoding="utf-8")

ps = (console / "PSForm.cs").read_text(encoding="utf-8-sig")
i = ps.index("unsafe static class puresignal")
i = ps.rindex("\n", 0, i) + 1
j = ps.index("\n    }\n", i) + len("\n    }\n")
(out_dir / "puresignal.g.cs").write_text(
    header.format(src="PSForm.cs")
    + "using System;\nusing System.Drawing;\nusing System.Runtime.InteropServices;\n\nnamespace Thetis\n{\n"
    + ps[i:j] + "}\n", encoding="utf-8")

print("regenerated", ", ".join(p.name for p in sorted(out_dir.glob("*.g.cs"))))
